name: setup-py
description: Reusable action for setting up a Python environment with pip requirements install

inputs:
  py-version:
    description: Python version
    default: '3.13'

  pip-requirements:
    description: Pip requirements path
    default: 'requirements.txt'

runs:
  using: composite

  steps:
    - uses: actions/setup-python@v6
      with:
        python-version: ${{ inputs.py-version }}

    - name: Install
      shell: bash
      env:
        PIP_DISABLE_PIP_VERSION_CHECK: '1'
      run: |
        python -m pip install --upgrade pip
        pip install -r "${{ inputs.pip-requirements }}"
