name: "GitHub Profile Repo Pins"
description: "Customizable public and private profile and Pages repo pins with themes, images, translations, and stats!"
author: "profile-icons"
branding:
  icon: "activity"
  color: "green"

inputs:
  gh_api_token:
    description: "GitHub PAT. Required for org profiles and private repo pins, but not for user profiles and public repo pins with workflow default: ${{ github.token }}"
    required: true
  gh_username:
    description: "GitHub username. Required for org, but not for user profiles with workflow default: ${{ github.repository_owner }}."
    required: true
  theme:
    description: "Theme name. Default is github_soft. Add themes at: profile-icons/readme-repo-pins-src."
    required: false
  background_image:
    description: "Background image (URL or file path)."
    required: false
  repo_names_exclusive:
    description: "Exclusive list of repositories (owner/repo) to render pins only for, separated by commas."
    required: false
  is_contribution_stats:
    description: "Include user contribution statistics (percentage). True (any input) or False (empty). Default False."
    required: false
  num_repo_pins:
    description: "Number of pins to render (capped at 100). Default is 6 or the number of repo_names_exclusive."
    required: false
  repo_pin_order:
    description: "The order of repo pins displayed. Default is stargazer count."
    required: false
  is_exclude_repos_owned:
    description: "Exclude owned repos not pinned. True (any input) or False (empty). Overridden by repo_names_exclusive."
    required: false
  is_exclude_repos_contributed:
    description: "Exclude contributed repos not owned or pinned. True (any input) or False (empty). Overridden by repo_names_exclusive."
    required: false

runs:
  using: "composite"
  steps:
    - name: Checkout repo
      uses: actions/checkout@v5
      with:
        token: ${{ inputs.gh_api_token }}
        fetch-depth: 0

    - name: Setup
      uses: actions/setup-python@v6
      with:
        python-version: '3.13'

    - name: Install
      shell: bash
      env:
        PIP_DISABLE_PIP_VERSION_CHECK: '1'
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run
      shell: bash
      env:
        GH_API_TOKEN: ${{ inputs.gh_api_token }}
        GH_USERNAME: ${{ inputs.gh_username }}
        GH_REPO_OWNER: ${{ github.repository_owner }}
        THEME: ${{ inputs.theme }}
        BG_IMG: ${{ inputs.background_image }}
        NUM_REPO_PINS: ${{ inputs.num_repo_pins }}
        REPO_PIN_ORDER: ${{ inputs.repo_pin_order }}
        REPO_NAMES_EXCLUSIVE: ${{ inputs.repo_names_exclusive }}
        IS_EXCLUDE_REPOS_OWNED: ${{ inputs.is_exclude_repos_owned }}
        IS_EXCLUDE_REPOS_CONTRIBUTED: ${{ inputs.is_exclude_repos_contributed }}
        IS_CONTRIBUTION_STATS: ${{ inputs.is_contribution_stats }}
      run: |
        python gh_profile_repo_pins.py

    - name: Commit
      shell: bash
      env:
        GH_USERNAME: ${{ inputs.gh_username }}
      run: |
        set -e
        FILES="$(ls README.md */README.md index.md imgs/*.svg 2>/dev/null | grep -v '^ls:' || true)"
        if [ -n "$FILES" ]; then
          git add $FILES
        fi
        if ! git diff --cached --quiet; then
          : "${GH_USER_NAME:?GH_USER_NAME missing}"; : "${GH_USER_ID:?GH_USER_ID missing}"
          git config user.name "$GH_USER_NAME"
          git config user.email "${GH_USER_ID}+${GH_USERNAME}@users.noreply.github.com"
          git commit -m "Auto-update profile repo pins"
          for attempt in 1 2 3; do
            git pull --rebase || true
            if git push; then
              exit 0
            fi
            echo "Push failed #$attempt"
            sleep $(((RANDOM % 8) + 3))
          done
          echo "Push failed after retries" >&2
          exit 1
        else
          echo "No changes to commit."
        fi
